ipfs-shipyard/ipfs-thing-2022

- devent.toml
> Add city location

- events/b_2_content-routing-1.toml
- events/b_3_content-routing-2.toml
- events/b_4_ipfs-wasm.toml
- events/c_1_ipfs_infra.toml
- events/c_2_project_and_community.toml
- events/c_3_data_transfer.toml
- events/d_1_identity_and_access_control copy.toml
- events/d_2_lite_clients.toml
- events/d_3_data_agony.toml
- website/components/event.js
marked nearly all tracks as works-in-progress
> adding a WIP tag dims the event card

- devent.toml
- website/components/about.js
- website/components/event.js
- website/components/hero.js
- website/components/markdown.js
- website/components/scheduleSection.js
- website/styles/global.css
Also adds an "Events are optional?" to the FAQ section
> show links in markdown text, description for schedule section

- devent.toml
- website/styles/global.css
Add FAQ on what it means to lead a track
> add track lead details to the FAQ

- events/d_2_data_agony.toml
- events/d_3_lite_clients.toml
> switch data agony to thu, move lite clients to fri, make lite clients half day

- events/a_2_hack-and-cowork.toml
to clarify that Saturday is still a day to hang & collaborate. Intentionally left without structure for the moment
> extend hack track into saturday

- devent.toml
minor updates to 2 parts of FAQ
> Remove invite-only language

- events/e_3_measuring_ipfs.toml
cc @yiannisbot, if you leave comments I can adjust the PR :)
> Add a measuring IPFS track

- events/b_1_ipfs-impls.toml
present and demo the IPFS operator
This is a turn-key IPFS cluster solution on kubernetes.
https://www.notion.so/pl-strflt/IPFS-operator-315aab3485bf4505a12e69ca0335ddd9
> ipfs operator

- events/d_3_browsers_and_mobile.toml
Hey all, I've restructured the "Lite Clients" track to include browsers and provide a goal for this half-day workshop. I'd love your feedback!
@RangerMauve & @matheus23, I'm asking for both of you (or someone from your org) to give lightning talks to help support this goal of moving the ball forward on IPFS in weird places. I'll wait for both of your feedback & approval before merging.
I'm also seeking feedback from folks I'd love to have attend:
@achingbrain
@autonome
@ikreymer
@lidel
@dignifiedquire
My first request for feedback: who else should we be trying to get to attend?
closes #31
> re-work lite clients into 'Browsers & Mobile'

- events/c_1_gateways.toml
- events/c_1_ipfs_as_infra.toml
@mikeal, can I shamelessly ask you to run a gateway track? I can help with structuring, but feel you or someone from your team would be a great fit to lead this track.
> mikeal leading infra track

- events/d_1_identity_and_access_control copy.toml
Renamed and added sessions for @expede @b5 and myself
> Update identity & access to Building Apps on IPFS

- events/c_3_project_and_community.toml
@autonome I created a placeholder for the standards conversation you mentioned in Discord. Feel free to edit the heck out of title & description.
Is 45 mins the right amount of time for the W3C & IETF topics? (@lidel's RFP (aka IPIP) session should cover how we're approaching the ipfs/specs repo going forward.)
> add external standards session to Project-and-Community

- README.md
- add definition of track and session
- make instructions more explicit
> update instructions for adding tracks & sessions

- .github/workflows/toml-validate.yml
Find all `.toml` files and assert that they are valid on push and PR.
Fixes: #51
> Recursively validate all TOML files in CI

- events/b_1_ipfs-impls.toml
https://github.com/2color/auspinner
> Add auspinner to implementations tracks

- events/b_2_content-routing-1.toml
- events/b_3_content-routing-2.toml
> move lunch breaks

- events/c_2_data_transfer.toml
@hannahhoward I'm making a bunch of shameless suggestions to help get you past blank-canvas syndrome on this track.  I've done a few things:
1. Drop the track length to half a day. Could be morning or afternoon
2. suggested a goal for the track: knowledge sharing! Feel free to nit-pick
3. I've dropped in a few suggested talks. As someone hoping to attend this track I'd _really_ like a brain dump from @hannahhoward on graphsync and a brain dump from @Stebalien on bitswap.
4. I'd like to talk about manifests.
But all of this is a suggestion. please change to suit your vision!
> suggest data transfer track structure

- events/e_3_measuring_ipfs.toml
These are the confirmed talks I have so far, although more might be coming, and more clarity around the afternoon slots will be added.
> Measurement Session Updates

- devent.toml
> Add Ceramic

- events/outing17.toml
Partner of #70, for Sunday 17th. Will update once Yuni locks outings details down.
> update sunday 17th social outings

- events/c_1_connecting-ipfs.toml
Moving this track to all 20m talks.
> fix: 20m talks

- events/b_1_ipfs-impls.toml
I want to cover a little more than just Elastic IPFS.
> Adjusting talk title and description

- events/c_3_project_and_community.toml
This was proposed in https://github.com/ipfs-shipyard/ipfs-thing-2022/issues/22 .  Just getting it on the list.  Happy to reschedule to whenever.
> Session on PL EngRes IPFS Development

- events/e_3_aqua_ipfs.toml
Proposing a new track about Aqua and IPFS on Thursday
> Add Aqua and IPFS track

- events/b_1_ipfs-impls.toml
addresses TOML errors in #103, supersedes #103
> add peergos talk to implementations track

- events/c_3_project_and_community.toml
Updated description to follow name change we did in (merged)  https://github.com/ipfs/specs/pull/289
> Update IPIP talk description

- events/b_2_content-routing-1.toml
> Reflect current timing

- events/c_3_project_and_community.toml
Shorten and rearrange sessions
> schedule tweaking

- events/c_3_project_and_community.toml
- add expede to content addressing alliance speakers
- fix a typo in track description
> clarify speakers

- package-lock.json
- website/components/NewConfBanner.js
- website/components/header.js
- website/package-lock.json
> add 2023 banner
