- devent.toml
- website/components/about.js
@b5 this PR begins the reorientation to community-led event that we discussed in this morning's call, and is ready for review and discussion!
- Renames everything "sponsors" to "teams"
- Adds Number Zero to Participating Teams list
- Updates the first 2 FAQs
There are several placeholders in the FAQs section. I've checked "Allow edits by maintainers" so feel free to edit directly. Up to you on whether to discuss and merge this set of changes, or wait until a more complete FAQ is done.
> Reorient to community

- devent.toml
- website/components/header.js
- Removed "About" since it's a duplicate of hero text, and "Venue" because it's not finalized yet and was rendering funny
- More details in "how to participate" FAQ
> logistics updates

- website/components/event.js
This changes event card display to feature organizers (labelled track chairs) instead of organizations, using the existing `dri` type.
Benefits:
- Submitters & participants can more easily see & contact the relevant track chair(s)
- Highlight the variety of organizers instead of Protocol Labs monolith
> highlight track chairs instead of organizations

- devent.toml
- remove dangling """ 
- fixes compilation & publishing
> bugfix: toml parse error: a """ was left behind

- website/components/event.js
This PR fixes the off by 1 error in how dates are displayed in the event card detail. I haven't written production js in many years, so please review the heck out of it (especially syntax).
Here's an example of the error. The metadata for this event only shows 1 day, but it renders as 2 days.
> fix off by 1 error in date display

- devent.toml
- website/components/hero.js
re-worked hero component layout for more consistent rendering across size breakpoints:
> re-work hero layout

- events/c_3_project_and_community.toml
This PR seeds the project & community track:
- Adds an RFC process session (speaker: @lidel)
- Adds an IPFS landing pages session as described in #3 (facilitator: @mishmosh) 
- Adds a placeholder session for project funding & sustainability (possible speakers: @b5 @mishmosh @autonome). Maybe we call it "Therapy session for reluctant CEOs" ;D
The duration is changed to 1/2 day until or unless we have enough material for a full day of programming. #12 also edits the same file and should be merged first, but there should be no merge conflicts.
> seed the project & community track

- devent.toml
Pretty much what it says on the tin. Fission is participating with I think 5 members planned to come.
(For linking purposes: https://github.com/fission-suite/ipfs-thing-2022/issues/1)
> Add Fission as attending team

- events/c_3_project_and_community.toml
I'd like to add a talk on [GitHub Management](https://github.com/protocol/github-mgmt-template) and, in particular, how we use it in [ipfs org](https://github.com/ipfs/github-mgmt) to the project and community track.
I'd like the main outcomes of the talk to be:
- users know how to request access to ipfs GitHub resources
- users know of GitHub Management and know where to find more information about it if they want to use it in other OS orgs
FYI, I'm not set on this time slot, I picked the first one that was available.
> add a talk on github-mgmt to project and community track

- events/b_4_ipfs-wasm.toml
If I want to add links or resources for the talk should that live in the description or elsewhere?
Note: Probably fine moving later in the day too if this slot was being reserved, but figured filling top down except when there's a conflict seemed reasonable.
> add wasm-ipld talk

- events/d_2_data_agony.toml
Gonna talk about IPLD on gateways and IPLD URLs.
We'll be looking at the proposed spec for IPLD on gateways, how it relates to URLs, and will be collecting feedback on the direction it should take and ideas for how it could be used.
Related: https://github.com/ipfs/specs/pull/293
> Add talk on IPLD in gateways to data agony track

- events/c_2_data_transfer.toml
This builds on #44 and fleshes out what I think the data transfer track should look like.
It's basically 4.5 hours of content + 15 min break and 1hr&15min for lunch (for 6 hours total -- I believe in ample break/lunch time). Next step is to coordinate with @aschmahmann to figure out how this and the data agony track line up so people can attend both in some kind of sequence. So essentially, actual time of day and other things are not set in stone. 
What is the best way to sequence this with data agony? Currently they are scheduled at the same time and I think that is not good. One suggestion:
- 1 structured day long track with data agony in the morning and data transfer in the afternoon
- a seperate afternoon track with all open slots for either category
> Additional revisions to data transfer track

- events/b_1_ipfs-impls.toml
I'm taking over Gateway slot (@gmasgras won't be attending).  Since this track is about "IPFS Implementations"  I'll give overview of past, present and future in the context of recently added [HTTP Gateway specs](https://github.com/ipfs/specs/tree/main/http-gateways) and their use (public gws, local nodes used  by Desktop/Brave/Companion/Agregore etc)
I already had Companion/Desktop, so I  swapped the order, as they use Gateways and it makes sense to talk about that first.
cc @autonome @hsanjuan
> Gateways and Companion/Desktop remix

- events/outing11.toml
Updating schedule around 11th/17th both being outing days, but no details announced yet. Right now makes the schedule looks like only outing is Golden Circle on 11th. We can add deets back in once Yuni locks it down.
> Update social outing days to make clear nothing specific announced yet

- events/d_3_browsers_and_web.toml
Multline strings in TOML are surrounded in triple quotes: `"""`
cc @autonome
> fix multiline strings in browsers_and_web track

- events/d_3_browsers_and_web.toml
Not sure about the timing. Maybe this should be earlier during the session, since this is exploring the basis connectivity options that libp2p nodes have at their disposal. I didn’t want to move anyone else’s talks though.
> add talk about Browser Connectivity

- events/b_2_content-routing-1.toml
I'm hoping future owners of these components in Kubo (@guseggert, @ajnavarro) can take this rather than legacy owner @aschmahmann .
> Assign owners to "State of content routing lightning talks"

- website/components/event.js
address an issue that crops up in #102 :
> prevent text overflow for track DRIs

- events/c_1_connecting-ipfs.toml
This PR adds the Elastic IPFS deep dive talk that Francisco is presenting.
I've also updated the title/description for the w3name talk and moved the "Rise of Elastic IPFS" talk to after Francisco's deep dive talk (it'll make more sense if this is presented afterwards).
> feat: add Elastic IPFS deep dive talk

- events/b_1_ipfs-impls.toml
- events/b_2_content-routing-1.toml
- events/b_3_content-routing-2.toml
- events/c_1_data_and_ipfs-1.toml
- events/c_2_data_and_ipfs-2.toml
- events/c_3_project_and_community.toml
- events/c_4_scalable-virtual-worlds.md
- events/d_1_connecting-ipfs.toml
- events/d_2_data_and_ipfs-3.toml
- events/d_3_browsers_and_web.toml
- events/d_3_ipfs-wasm.toml
- events/d_3_roadmap.toml
- events/e_3_aqua_ipfs.toml
- events/e_3_measuring_ipfs.toml
See https://github.com/ipfs-shipyard/ipfs-thing-2022/issues/110 for context
Here are the list of files/tracks/URLs added:
```
b_1_ipfs-impls	🛤 2022-07-12: IPFS Implementations	https://discuss.ipfs.io/t/2022-07-12-ipfs-implementations/14632
b_2_content-routing-1	🛤 2022-07-13: Content Routing 1: Performance	https://discuss.ipfs.io/t/2022-07-13-content-routing-1-performance/14633
b_3_content-routing-2	🛤 2022-07-14: Content Routing 2: Privacy	https://discuss.ipfs.io/t/2022-07-14-content-routing-2-privacy/14634
c_1_data_and_ipfs-1	🛤 2022-07-13: Data and IPFS: Models	https://discuss.ipfs.io/t/2022-07-13-data-and-ipfs-models/14635
c_2_data_and_ipfs-2	🛤 2022-07-14: Data And IPFS: Transfer	https://discuss.ipfs.io/t/2022-07-14-data-and-ipfs-transfer/14636
c_3_project_and_community	🛤 2022-07-15: …
```
> Add IPFS Discourse topic "website" links for each track

- events/d_3_browsers_and_web.toml
Wanted to claim a lightning talk spot for a quick ~10 min overview of Webrecorder tools and our various use cases for IPFS in the browser. If 10 min is too long, can probably get it down to 5 min..
> Add Webrecorder lightning talk for Browsers and the Web

- website/components/event.js
- website/components/scheduleSection.js
- website/components/scheduletable.js
- website/lib/annotateEvents.js
- website/lib/dayOffset.js
- website/lib/genDates.js
---
If we don't want 2, let me know, I would just need to revert `'feat: modal open/close uses window.history'` 
fixes #125
> feat: Add event modal deep-linking

- devent.toml
- website/components/hero.js
Remove the recap link.
Instead link to where one can read a recap and watch the videos.
This can't be merged until https://github.com/ipfs/ipfs-blog/issues/443 is addressed.
> Converting RSVP link to recap link
